image: node:14

# Workflow Configuration
pipelines:

  branches:
    develop:
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:1.2.1
      - step:
          name: Build
          script:
            - npm install -g @angular/cli
            - npm ci
            - ng build --prod
            - find dist/
          artifacts:
            - dist/**

      - step:
          name: DEV - deploy to S3
          deployment: dev
          clone:
            enabled: false
          script:            
            # copy files to S3
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_DEFAULT_REGION: us-east-2
                S3_BUCKET: hum-dev-portal-files
                LOCAL_PATH: "dist/Humaine-Web/"
                DELETE_FLAG: "true"
            # triggering a distribution invalidation to refresh the CDN caches
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_DEFAULT_REGION: us-east-1
                DISTRIBUTION_ID: EP0A5RE66UKUW

      - step:
          name: PROD - deploy to S3
          deployment: prod
          clone:
            enabled: false
          script:            
            # copy files to S3
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_DEFAULT_REGION: us-east-2
                S3_BUCKET: hum-prod-portal-files
                LOCAL_PATH: "dist/Humaine-Web/"
                DELETE_FLAG: "true"
            # triggering a distribution invalidation to refresh the CDN caches
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_DEFAULT_REGION: us-east-1
                DISTRIBUTION_ID: E2IMQV0O0U8O21
