
export interface IHeatMapImages {
    "PRODUCT-CATEGORY": Cart;
    "PRODUCT-DETAILS":  Cart;
    HOME:               Cart;
    CART:               Cart;
}

export class Cart {
    tablet:  Desktop ;
    desktop: Desktop;
    mobile:  Desktop;
}

export class Desktop {
    id:       number = null;
    category: string = null;
    device:   Device = null;
    pageUrl:  string = null;
}

// Generated by https://quicktype.io

export class IDeviceType {
    tablet:  string = '';
    desktop: string = '';
    mobile:  string = '';
}


export enum Device {
    Desktop = "desktop",
    Mobile = "mobile",
    Tablet = "tablet",
}

