// Generated by https://quicktype.io


export class LastRefreshTime {
    lastRefresh: string = null;
}

export class ITopCountries {
    activeStates: ActiveState[] = [];
}

export class ActiveState {
    state: string = null;
    soldAmount: number = null;
}
// Generated by https://quicktype.io

export class ITileChart {
    totalSessions: TotalSessions = null;
    overallConversionRate: ActiveUsers = null;
    totalConversions: ActiveUsers = null;
    activeUsers: ActiveUsers = null;
    averageSpend: ActiveUsers = null;
    bounceRate: BounceRate = null;
}

export class ActiveUsers {
    data: { [key: string]: number } = null;
    totalCount: number | null = null;
    percentageCount: number | null = null;
    lastHourComparison: number | null = null;
}

export class TotalSessions {
    hourWiseData: HourWiseData = null;
    count: number = null;
    lastHourComparison: number | null = null;
}

export interface HourWiseData {
    "11": number;
}

export class BounceRate {
    data: { [key: string]: number } = null;
    totalCount: number | null = null;
    percentageCount: number | null = null;
    lastHourComparison: number | null = null;
}
