// Generated by https://quicktype.io


export interface IElements {
    id: number;
    values: Value[];
    name: string;
    isSkip: boolean;
    showMore: boolean;
}

export interface Value {
    id: number;
    value: string;
}

export interface ITestJourneyUser {
    name: string;
    groupId: number;
}


export class ISaveTestJourney {
    decison: string = "";
    firstInterest: string = "";
    groupId: number = null;
    purchaseAddCart: string = "";
    purchaseBuy: string = "";
    purchaseOwnership: string = "";
    totalJourneySteps: number = null;
    journeySteps: number = null;
    id: number = null;
    journeyTime: string = ""
    successRate:string = "";
    groupName: string = "";
    bigFive: string = "";
}