// Generated by https://quicktype.io

export interface IUserGroupCreate {
    ageGroup:              number;
    bigFive:               number;
    ethnicity:             number;
    familySize:            number;
    gender:                number;
    isExternalFactor:      boolean;
    motivationToBuy:       number;
    name:                  string;
    persuasiveStratergies: number;
    state:                 string;
    values:                number;
    education:             number;
}

export interface IDemographicData {
    gender:     Gender[];
    education:  Attribute[];
    ageGroup:   Attribute[];
    ethnicity:  Attribute[];
    familySize: Attribute[];
    bigFive:    Attribute[];
}

export interface Attribute {
    id:    number;
    value: string;
}

export interface Gender {
    id:      number;
    value:   string;
    isOther: boolean;
}

export interface IcognitiveData {
    motivationToBuy:           Attribute[];
    motivationToBuyEmpty:      Attribute;
    persuasiveStrategies:      Attribute[];
    persuasiveStrategiesEmpty: Attribute;
    values:                    Attribute[];
    valuesEmpty:               Attribute;
}

export interface MotivationToBuyEmpty {
    id:    number;
    value: string;
}


export class IviewUserGroupStatistics{
    averageSpend : any[];
    overallConversionRate : any[]
}

export class IUserGroupList {
    groupId:               number;
    name:                  string;
    gender:                string;
    ageGroup:              string;
    state:                 string;
    ethnicity:             string;
    familySize:            string;
    isExternalFactor:      boolean;
    bigFive:               string;
    values:                string;
    persuasiveStratergies: string;
    motivationToBuy:       string;
    education:             string;
    icon:                  string;
    checked:               boolean;
}

export class IUserGroupListData extends IUserGroupList {
    checked: boolean;
}


