// Generated by https://quicktype.io

export class IUXInsight {
    totalUsers:           number = null;
    dailyAvgSessions:     number = null;
    dailyPurchaseProduct: number = null;
    dailyAvgSale:         number = null;
}

export class IUXInsightProduct {
    mostViewProducts:      MostProduct[] = [];
    mostPurchasedProducts: MostProduct[] = [];
    mostViewCategory:      MostViewCategory[] = [];
    eventCounts = new eventCounts();
}

export interface MostProduct {
    productName:     string;
    productPageURL:  string;
    clickCount:      number;
    purchasedCount?: number;
    purchaseCount?:  number;
}

export interface MostViewCategory {
    category:          string;
    clickCount:        number;
    categoryViewCount: number;
    pageUrl:           null;
}

export class eventCounts {
    blogPostEventPercentage: number = null;
    buyPercentage: number = null;
    otherPercentage:number = null;
    productViewPercentage:number = null;
    reviewPercentage:number = null;
    wishListPercentage:number = null;
}

